import { describe, it, expect, vi } from 'vitest'
import { readFileSync } from 'node:fs'

// Conformance against the canonical address table in api/ssrf-vectors.json.
//
// The same policy is implemented across three GLANCE repositories, separately
// on purpose (a Vercel function here, plain ESM copied into a Docker image in
// dayGLANCE, strict TypeScript in its Electron bundle). A range added to one
// and forgotten in another is the drift that produced those divergent copies to
// begin with, so each repo commits the same vectors file and checks its own
// implementation against it. Same idea as dayDial.vectors.json keeping the JS
// and Swift dial geometry in agreement.
//
// The file is generated by scripts/export-ssrf-vectors.mjs in krelltunez/
// dayGLANCE and copied here verbatim. Do not hand-edit it: change the policy
// there, regenerate, copy, and run this suite.
//
// If this fails, do not relax it. Either this repo's implementation drifted, or
// the table changed and this copy is stale.

const vectorFile = JSON.parse(readFileSync('api/ssrf-vectors.json', 'utf-8'))
const vectors = vectorFile.vectors

// The vectors are addresses, so the hostname resolution is stubbed per case and
// validateProxyUrl is driven through its real entry point. That way the test
// exercises what actually runs in production rather than an internal predicate,
// and the same table works for repos whose classifier is not exported.
let resolved = []
vi.mock('dns/promises', () => ({
  lookup: async () => resolved,
}))

const { validateProxyUrl, isPrivateIPv4, isPrivateIPv6, isAlwaysBlockedIPv4, isAlwaysBlockedIPv6 } =
  await import('./webdav-proxy.js')

const HOSTED = { allowPrivate: false }
const SELF_HOSTED = { allowPrivate: true }
const PRIVATE_ERR = 'Private/reserved addresses are not allowed'

describe('ssrf-vectors.json', () => {
  it('is the shape this suite expects', () => {
    expect(vectorFile.version).toBe(1)
    expect(vectorFile.postures).toEqual({
      hosted: { allowPrivate: false, description: 'a shared cloud deployment' },
      selfHost: { allowPrivate: true, description: "an instance on the operator's own network" },
    })
    expect(vectors.length).toBeGreaterThan(40)
    expect([...new Set(vectors.map(v => v.class))].sort()).toEqual(['always', 'ok', 'private'])
  })
})

describe('the predicates classify every vector as the table says', () => {
  it.each(vectors.map(v => [v.address, v.family, v.class, v.note]))(
    '%s (%s) is %s: %s',
    (address, family, cls) => {
      const always = family === 4 ? isAlwaysBlockedIPv4(address) : isAlwaysBlockedIPv6(address)
      const priv = family === 4 ? isPrivateIPv4(address) : isPrivateIPv6(address)
      expect({ always, priv }).toEqual({ always: cls === 'always', priv: cls !== 'ok' })
    },
  )
})

describe('validateProxyUrl produces the table verdict in both postures', () => {
  it.each(vectors.map(v => [v.address, v.family, v.hosted, v.note]))(
    'hosted: %s (%s) -> %s: %s',
    async (address, family, verdict) => {
      resolved = [{ address, family }]
      const call = validateProxyUrl('https://target.example.com/dav/', HOSTED)
      if (verdict === 'allow') await expect(call).resolves.toBeTruthy()
      else await expect(call).rejects.toThrow(PRIVATE_ERR)
    },
  )

  it.each(vectors.map(v => [v.address, v.family, v.selfHost, v.note]))(
    'self-host: %s (%s) -> %s: %s',
    async (address, family, verdict) => {
      resolved = [{ address, family }]
      const call = validateProxyUrl('https://target.example.com/dav/', SELF_HOSTED)
      if (verdict === 'allow') await expect(call).resolves.toBeTruthy()
      else await expect(call).rejects.toThrow(PRIVATE_ERR)
    },
  )
})
